### ISSUE TITLE
Can't found file name ur5_robotiq_85.urdf

### ISSUE THREAD

**Issue by HanwenWangBUPT** [Gary3410/Smart-Explorer#2]
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,152]:
URDF file './urdf/ur5_robotiq_85.urdf' not found
Traceback (most recent call last):
  File "test_push.py", line 1464, in <module>
    main()
  File "test_push.py", line 1216, in main
    robot.load()
  File "/home/hanwen.wang/code1/Smart-Explorer-main/robot.py", line 40, in load
    self.__init_robot__()
  File "/home/hanwen.wang/code1/Smart-Explorer-main/robot.py", line 176, in __init_robot__
    useFixedBase=True, flags=p.URDF_ENABLE_CACHED_GRAPHICS_SHAPES)
pybullet.error: Cannot load URDF file.

**Comment by Gary3410** [comment]
The urdf files have been uploaded. More details can be found [here](https://github.com/ElectronicElephant/pybullet_ur5_robotiq).
