### ISSUE TITLE
A bug in "test_push.py",line1280.IndexError: tuple index out of range

### ISSUE THREAD

**Issue by HanwenWangBUPT** [Gary3410/Smart-Explorer#3]
Execuse me,I meet a bug in "test_push.py",line1280.I printed the contents of the "t[]" list and looked at the program of the "postprocess "function, and I found that there are only 4 elements in the "t[]" list, but in line 1280 I need to use the element t[4] to operate, which means that I used the fifth element of the t list, which creates a conflict, could you please help me analyze the problem, thanks.

bug details:
Traceback (most recent call last):
  File "test_push.py", line 1464, in <module>
    main()
  File "test_push.py", line 1280, in main
    segment_map = t[4].permute(1, 2, 0).clone()
IndexError: tuple index out of range

**Comment by HanwenWangBUPT** [comment]
谢谢学长，已经没问题了。
